version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - /path/to/prometheuse.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - /path/to/grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  freebox-monitoring:
    image: freebox-monitoring
    container_name: freebox-monitoring
    restart: always
    volumes:
      - /path/to/token:/token
    networks:
      - monitoring

networks:
  monitoring:
